FROM java:8

COPY target/CucumberBasic-1.0-SNAPSHOT-jar-with-dependencies.jar CucumberBasic-1.0-SNAPSHOT-jar-with-dependencies.jar

CMD ["java", "-Dfile.encoding=UTF-8 ", "-jar", "CucumberBasic-1.0-SNAPSHOT-jar-with-dependencies.jar"]
